---
- name: Setup Jenkins Worker
  hosts: jenkins_slave
  become: true
  vars:
    jenkins_master_url: "http://18.184.193.25:8080"
    jenkins_agent_name: "worker-1"
    jenkins_secret: "PASTE_AGENT_SECRET_HERE"
    jenkins_agent_dir: "/opt/jenkins"

  tasks:
    - name: Install required packages
      dnf:
        name:
          - java-21-amazon-corretto
          - wget
          - git
        state: present

    - name: Create agent directory
      file:
        path: "{{ jenkins_agent_dir }}"
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Download agent.jar from Jenkins master
      get_url:
        url: "{{ jenkins_master_url }}/jnlpJars/agent.jar"
        dest: "{{ jenkins_agent_dir }}/agent.jar"
        mode: '0755'

    - name: Start Jenkins agent in background
      shell: |
        nohup java -jar {{ jenkins_agent_dir }}/agent.jar -jnlpUrl {{ jenkins_master_url }}/computer/{{ jenkins_agent_name }}/jenkins-agent.jnlp -secret {{ jenkins_secret }} -workDir "{{ jenkins_agent_dir }}" &
      args:
        creates: "{{ jenkins_agent_dir }}/agent.jar"