---
- name: Setup NGINX on Jenkins Master
  hosts: jenkins_master
  become: true

  tasks:
    - name: Install NGINX
      dnf:
        name: nginx
        state: present

    - name: Copy NGINX config for Jenkins
      copy:
        src: nginx-default.conf
        dest: /etc/nginx/conf.d/default.conf
        owner: root
        group: root
        mode: '0644'

    - name: Restart and enable NGINX
      service:
        name: nginx
        state: restarted
        enabled: true
      