global:
  resolve_timeout: 5m

route:
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: telegram-notifications
  routes:
    - matchers:
        - alertname=~".*"
      receiver: telegram-notifications

receivers:
  - name: 'telegram-notifications'
    telegram_configs:
      - bot_token: '7306819995:AAF8iJP9JnnOFTZy7s112Nuvpslk-C1ja2E'
        chat_id: 194955
        parse_mode: 'Markdown'
        message: |
          🔔 *Alert:* {{ .CommonLabels.alertname }}
          *Status:* {{ .Status }}
          *Severity:* {{ .CommonLabels.severity }}
          *Description:* {{ .CommonAnnotations.summary }}