apiVersion: v1
kind: Service
metadata:
  name: python-random-service
spec:
  type: NodePort
  selector:
    app: python-random
  ports:
    - protocol: TCP
      port: 80            
      targetPort: 8082    
      nodePort: 30080 